FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

COPY entrypoint.sh /
RUN chmod +x /entrypoint.sh

RUN npm install

COPY . .

EXPOSE 8080

ENTRYPOINT [ "/entrypoint.sh" ]
