FROM node:18

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

COPY entrypoint.sh .
RUN chmod +x ./entrypoint.sh

COPY wait-for-it.sh .
RUN chmod +x ./wait-for-it.sh

RUN npm install

COPY . .

EXPOSE 8080

ENTRYPOINT [ "/usr/src/app/entrypoint.sh" ]
